# Generated by Django 4.2.5 on 2023-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
                ('user', models.CharField(default='', max_length=300)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
